In [1]:
from pandas import read_csv, DataFrame
import re
import itertools

In [2]:
cd C:\\Users\\8410106\\Documents\\Data

C:\Users\8410106\Documents\Data

In [3]:
#Import
telNums = read_csv('TelNums.csv')

In [15]:
#Remove whiteSpace
def removeWhiteSpace (y):
    #y = y.strip()
    z = y.replace(" ", "")
    return z

In [16]:
#Lets replace question marks and merge the two columns into 1 with no spaces
telNums['TEL_ARA_CD'] = telNums['TEL_ARA_CD'].str.replace('?',' ')
telNums["Merged"] = telNums["TEL_ARA_CD"] + telNums["TEL_NO"]
telNums["MergedNoSpace"] = telNums["Merged"].apply(removeWhiteSpace)

In [17]:

telNums

,TEL_ARA_CD,TEL_NO,Merged,MergedNoSpace,Validation
0,,88888888888888888888,88888888888888888888,88888888888888888888,0
1,,,,,0
2,01458,831335,01458 831335,01458831335,0
3,01375,380165,01375 380165,01375380165,0
4,,01417713396,01417713396,01417713396,0
5,,01413323383,01413323383,01413323383,0
6,,01292445646,01292445646,01292445646,0
7,,02840626499,02840626499,02840626499,0
8,01934,528384,01934 528384,01934528384,0
9,,07967148059,07967148059,07967148059,0
10,01740,655725,01740 655725,01740655725,0
11,01704,821584,01704 821584,01704821584,0
12,7507,315822,7507 315822,7507315822,0
13,0141,5798765,0141 5798765,01415798765,0
14,0141,5711174,0141 5711174,01415711174,0
15,01252,677710,01252 677710,01252677710,0
16,01244,540985,01244 540985,01244540985,0
17,,01179507235,01179507235,01179507235,0
18,01384,826291,01384 826291,01384826291,0
19,01223,806384,01223 806384,01223806384,0
20,0141,5712574,0141 5712574,01415712574,0
21,01276,623330,01276 623330,01276623330,0
22,01603,813508,01603 813508,01603813508,0
23,0141,5600861,0141 5600861,01415600861,0
24,01484,513865,01484 513865,01484513865,0
25,,01623645244,01623645244,01623645244,0
26,01509,505464,01509 505464,01509505464,0
27,,02087220545,02087220545,02087220545,0
28,0118,9834372,0118 9834372,01189834372,0
29,,01698329698,01698329698,01698329698,0
...,...,...,...,...,...
970,01673,866443,01673 866443,01673866443,0
971,,01268417940,01268417940,01268417940,0
972,,0161 7759896,0161 7759896,01617759896,0
973,,01344 421835,01344 421835,01344421835,0
974,,01213566454,01213566454,01213566454,0
975,,01213544473,01213544473,01213544473,0
976,0121,7064598,0121 7064598,01217064598,0
977,,01704570962,01704570962,01704570962,0
978,01275,839069,01275 839069,01275839069,0
979,,07790978560,07790978560,07790978560,0
980,,01856741343,01856741343,01856741343,0
981,,9564154,9564154,9564154,0
982,,01325466461,01325466461,01325466461,0
983,01908,310044,01908 310044,01908310044,0
984,9999,999999,9999 999999,9999999999,0
985,0141,7776309,0141 7776309,01417776309,0
986,,88888888888888888888,88888888888888888888,88888888888888888888,0
987,0191,01912626753,0191 01912626753,019101912626753,0
988,01375,892137,01375 892137,01375892137,0
989,01604,246937,01604 246937,01604246937,0
990,,01535 664901,01535 664901,01535664901,0
991,,01535664901,01535664901,01535664901,0
992,,88888888888888888888,88888888888888888888,88888888888888888888,0
993,,88888888888888888888,88888888888888888888,88888888888888888888,0
994,,07740093952,07740093952,07740093952,0
995,,07740093952,07740093952,07740093952,0
996,,01656652606,01656652606,01656652606,0
997,,07940494263,07940494263,07940494263,0
998,,09407654,09407654,09407654,0
999,,07912610238,07912610238,07912610238,0

In [39]:
def validateTelNum (x):
    rule = re.compile('^\s*\(?(020[78]\)? ?[1-9][0-9]{2} ?[0-9]{4})|(0[1-8][0-9]{3}\)? ?[1-9][0-9]{2} ?[0-9]{3})\s*$')
    chain = itertools.chain(*rule.findall(x))
    if x in list(chain):
        return 1
    else: 
        return 0

In [43]:
validateTelNum('018845292')

0

In [44]:
telNums["Validation"] = telNums["MergedNoSpace"].apply(validateTelNum)

In [45]:
telNums

,TEL_ARA_CD,TEL_NO,Merged,MergedNoSpace,Validation
0,,88888888888888888888,88888888888888888888,88888888888888888888,0
1,,,,,0
2,01458,831335,01458 831335,01458831335,1
3,01375,380165,01375 380165,01375380165,1
4,,01417713396,01417713396,01417713396,1
5,,01413323383,01413323383,01413323383,1
6,,01292445646,01292445646,01292445646,1
7,,02840626499,02840626499,02840626499,1
8,01934,528384,01934 528384,01934528384,1
9,,07967148059,07967148059,07967148059,1
10,01740,655725,01740 655725,01740655725,1
11,01704,821584,01704 821584,01704821584,1
12,7507,315822,7507 315822,7507315822,0
13,0141,5798765,0141 5798765,01415798765,1
14,0141,5711174,0141 5711174,01415711174,1
15,01252,677710,01252 677710,01252677710,1
16,01244,540985,01244 540985,01244540985,1
17,,01179507235,01179507235,01179507235,1
18,01384,826291,01384 826291,01384826291,1
19,01223,806384,01223 806384,01223806384,1
20,0141,5712574,0141 5712574,01415712574,1
21,01276,623330,01276 623330,01276623330,1
22,01603,813508,01603 813508,01603813508,1
23,0141,5600861,0141 5600861,01415600861,1
24,01484,513865,01484 513865,01484513865,1
25,,01623645244,01623645244,01623645244,1
26,01509,505464,01509 505464,01509505464,1
27,,02087220545,02087220545,02087220545,1
28,0118,9834372,0118 9834372,01189834372,1
29,,01698329698,01698329698,01698329698,1
...,...,...,...,...,...
970,01673,866443,01673 866443,01673866443,1
971,,01268417940,01268417940,01268417940,1
972,,0161 7759896,0161 7759896,01617759896,1
973,,01344 421835,01344 421835,01344421835,1
974,,01213566454,01213566454,01213566454,1
975,,01213544473,01213544473,01213544473,1
976,0121,7064598,0121 7064598,01217064598,0
977,,01704570962,01704570962,01704570962,1
978,01275,839069,01275 839069,01275839069,1
979,,07790978560,07790978560,07790978560,1
980,,01856741343,01856741343,01856741343,1
981,,9564154,9564154,9564154,0
982,,01325466461,01325466461,01325466461,1
983,01908,310044,01908 310044,01908310044,1
984,9999,999999,9999 999999,9999999999,0
985,0141,7776309,0141 7776309,01417776309,1
986,,88888888888888888888,88888888888888888888,88888888888888888888,0
987,0191,01912626753,0191 01912626753,019101912626753,0
988,01375,892137,01375 892137,01375892137,1
989,01604,246937,01604 246937,01604246937,1
990,,01535 664901,01535 664901,01535664901,1
991,,01535664901,01535664901,01535664901,1
992,,88888888888888888888,88888888888888888888,88888888888888888888,0
993,,88888888888888888888,88888888888888888888,88888888888888888888,0
994,,07740093952,07740093952,07740093952,0
995,,07740093952,07740093952,07740093952,0
996,,01656652606,01656652606,01656652606,1
997,,07940494263,07940494263,07940494263,1
998,,09407654,09407654,09407654,0
999,,07912610238,07912610238,07912610238,1